# Generated by Django 5.2.17 on 2026-09-28 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='transport.rank'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='accounts.rankcode'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_applications', to='accounts.rankcode'),
        ),
    ]
