# Generated by Django 5.2.17 on 2026-09-29 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drivercomplaint',
            constraint=models.UniqueConstraint(fields=('trip', 'raised_by'), name='unique_complaint_per_passenger_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='driverrating',
            constraint=models.UniqueConstraint(fields=('driver', 'trip', 'passenger'), name='unique_rating_per_passenger_per_trip'),
        ),
    ]
